# Generated by Django 2.2.5 on 2021-07-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('foodPrice', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
