# Generated by Django 2.2.5 on 2021-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_orderdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailySales', models.FloatField()),
                ('weeklySales', models.FloatField()),
                ('monthlySales', models.FloatField()),
                ('yearlySales', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
