# Generated by Django 2.2.5 on 2021-07-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210705_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.CharField(max_length=100)),
                ('totalSales', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
