# Generated by Django 2.2.5 on 2021-07-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
