# Generated by Django 2.2.5 on 2021-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noId', models.PositiveIntegerField()),
                ('day', models.CharField(max_length=100)),
                ('sales', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
