# Generated by Django 2.2.5 on 2021-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20210720_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noId', models.PositiveIntegerField()),
                ('dayly', models.CharField(max_length=100)),
                ('sales', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noId', models.PositiveIntegerField()),
                ('monthly', models.CharField(max_length=100)),
                ('sales', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YearlySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noId', models.PositiveIntegerField()),
                ('yearly', models.CharField(max_length=100)),
                ('sales', models.PositiveIntegerField()),
            ],
        ),
    ]
